### PR TITLE
Fix debug build error of the undefined inROMClass() in ClassEnv

### LINKED ISSUE #7518: Build failure with J9ClassEnv.cpp
Two calls to `inROMClass()` in `J9::ClassEnv::getROMClassRefName()` cause a build failure when you enable `TR_ASSERT()` as shown below:

>/root/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/compiler/../compiler/env/J9ClassEnv.cpp: In member function 'uint8_t* J9::ClassEnv::getROMClassRefName(TR::Compilation*, TR_OpaqueClassBlock*, uint32_t, int&)':
>/root/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/compiler/../compiler/env/J9ClassEnv.cpp:520:14: error: 'inROMClass' was not declared in this scope
>    TR_ASSERT(inROMClass(romFieldRef), "field ref must be in ROM class");

### PR DESCRIPTION
**Pull request by a7ehuo**
Remove the `TR_ASSERTs` for now. `TR_ASSERTs` are added in #7292 but `inROMClass()` is not declared/defined for `ClassEnv`.

Fix #7518

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@mpirvu Could you help review this one? Thanks! This should fix the debug build error introduced by #7487.

**Comment by mpirvu** [comment]
Jenkins compile xlinux jdk8

**Comment by mpirvu** [comment]
Compilation tests are sufficient because this PR only eliminated a couple of asserts
