### ISSUE TITLE
OpenJ9 build failure: sun_misc_Unsafe.cpp No Such Instruction 

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#8725]
OpenJ9 is failing to build on linux_x64 and linux_x64_XL machines with the following error. 
```
common/sun_misc_Unsafe.cpp: Assembler messages:
common/sun_misc_Unsafe.cpp:887: Error: no such instruction: `clflushopt (%rdx)'
common/sun_misc_Unsafe.cpp:889: Error: no such instruction: `clflushopt (%rcx)'
common/sun_misc_Unsafe.cpp:880: Error: no such instruction: `clwb (%rdx)'
common/sun_misc_Unsafe.cpp:883: Error: no such instruction: `clwb (%rcx)'
../makelib/targets.mk:283: recipe for target 'sun_misc_Unsafe.o' failed
```
Currently fails on all jdk11 and 14 linux and linux_xl builds and on jdk8 linux_xl builds (jdk8 linux is failing for the known  `#include "net/gen/compile.pb.h"` failure) 

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/497/console

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Can you look into this?  I suspect it's related to the Unsafe changes for Nonvolatile memory

**Comment by keithc-ca** [comment]
On the surface, this seems likely to be a compiler version or machine issue.
The compiler path in the log suggests the build is using gcc-7.5: Does anyone know if the build host has to support those instructions for the assembler to accept them?
What version of `as` is in use?

**Comment by AdamBrousseau** [comment]
@M-Davies can you include the git SHAs that were used to build please? I can't find them from the console output. I don't see any failures on internal builds or at the OpenJ9 farm.

**Comment by pshipton** [comment]
We know the problem is introduced by https://github.com/eclipse/openj9/pull/7258 which was recently merged. What we don't yet understand is why it builds on the OpenJ9 machines but not on the Adopt machines (https://github.com/eclipse/openj9/issues/8725#issuecomment-593974047).

**Comment by pshipton** [comment]
and for the record, the `#include "net/gen/compile.pb.h"` problem is https://github.com/eclipse/openj9/issues/8681 which has a PR under review to fix it, https://github.com/eclipse/openj9/pull/8730.

**Comment by M-Davies** [comment]
@AdamBrousseau I could only see the following SHA from the output
```
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (fetch)
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (push)
jdk11
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (fetch)
Resetting the git openjdk source repository at /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9/workspace/build/src in 10 seconds...
Pulling latest changes from git openjdk source repository
Fetching origin
From https://github.com/ibmruntimes/openj9-openjdk-jdk11
   ec6edb1c55..e0e94184e0  openj9         -> origin/openj9
   ea83fead1e..0762977448  master         -> origin/master
   f4e1e81163..14d3d2ec1e  openj9-staging -> origin/openj9-staging
 * [new tag]               jdk-11.0.7+5   -> jdk-11.0.7+5
HEAD is now at e0e94184e0 Merge pull request #270 from keithc-ca/debug-image

OpenJDK repo tag is jdk-11.0.7+5

Tools summary:
* Boot JDK:       openjdk version "10.0.2-adoptopenjdk" 2018-07-17 OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13) OpenJDK 64-Bit Server VM (build 10.0.2-adoptopenjdk+13, mixed mode)  (at /usr/lib/jvm/jdk-10.0.2+13)
* Toolchain:      gcc (GNU Compiler Collection)
* C Compiler:     Version 7.5.0 (at /usr/local/gcc/bin/gcc-7.5)
* C++ Compiler:   Version 7.5.0 (at /usr/local/gcc/bin/g++-7.5)
```

Have raised a query in the adopt infrastructure channel about the version of `as` we're using https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1583252454023800

**Comment by M-Davies** [comment]
@keithc-ca We have as versions 2.20, 2.23 and 2.28 installed on the machine however it's not clear which one we use in the build scripts.

**Comment by sxa555** [comment]
It may be 2.20 which I believe is older than the one used on the OpenJ9 machines

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/552/consoleFull /should/ have been run with `as` 2.28 but still failed

**Comment by keithc-ca** [comment]
In a CentOS:6.9 docker container, `as` reports:
```
# as --version
GNU assembler version 2.20.51.0.2-5.48.el6_10.1 20100205
```
and `gcc-7.5` complains the similarly:
```
# gcc --version
gcc (GCC) 7.5.0
# gcc -c test.c 
test.c: Assembler messages:
test.c:3: Error: no such instruction: `clwb (%rax)'
test.c:4: Error: no such instruction: `clflushopt (%rax)'
```
We need to find another way to express those instructions in our code or upgrade the assembler on build machines.

**Comment by mikezhang1234567890** [comment]
`as` version 2.25 seems to be the earliest version with clwb/clflushopt.

**Comment by sxa555** [comment]
Hmmm so my test with replacing the `/usr/bin/as` symlink should have worked. May try that again tomorrow ...

**Comment by keithc-ca** [comment]
> @keithc-ca We have as versions 2.20, 2.23 and 2.28 installed on the machine however it's not clear which one we use in the build scripts.

Why three versions?

**Comment by sxa555** [comment]
> > @keithc-ca We have as versions 2.20, 2.23 and 2.28 installed on the machine however it's not clear which one we use in the build scripts.
> Why three versions?

OS Default, devtoolset-2 and devtoolset-7 which have all been required at one time or another and haven't been removed

**Comment by DanHeidinga** [comment]
@AdamBrousseau @jdekonin Do you know which version of `as` is used on the openj9 machines?  Does it match the playbook version?

**Comment by jdekonin** [comment]
devtoolset-7 comes with its own version of `as` if you are using the enable script provided with that package.  gcc-7.3, on older os level, requires new binutils...ld, as for certain.  I believe v2.28 or higher is required for gcc7. 

I found this related PR, which ended up closed around the time 7.5 was starting to be introduced??  Either way, gcc-7.5 would have the same requirement of requiring a newer binutils.  If gcc-7.5 is being compiled from source as on the OpenJ9 Linux machines, then binutils needs to also be done if its not at a new enough level.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/598

**Comment by mikezhang1234567890** [comment]
As a temporary measure we could change `writebackMemory` to only use the `clflush` instruction. @DanHeidinga do you want me to create that PR?

**Comment by keithc-ca** [comment]
From my understanding, using `clflush` exclusively would have performance consequences: I don't think that's a good idea.

**Comment by DanHeidinga** [comment]
I agree with Keith.  We don't want to limit the implementation if we can address this with the infrastructure.  My understanding is that @sxa555 is looking going to give using the newer `as` on the Adopt machine another try

**Comment by sxa555** [comment]
@jdekonin What made you choose 2.28? Violete's proposed PR was 2.31 so I assumed that's what you'd put on  your systems

**Comment by jdekonin** [comment]
iirc that is just what we have a tar of based on initial build and test on gcc7 and we just haven't been back to updating.

**Comment by sxa555** [comment]
FYI @jdekonin freetype doesn't appear to quite work successfully when build using the binutils 2.31 tools (the configure step of the jdk codebase doesn't detect it properly) but does when freetype is linked using 2.28:
```
configure: Found freetype include files at /home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/./build//installedfreetype/include using --with-freetype
checking for freetype includes... /home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/build/installedfreetype/include
checking for freetype libraries... /home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/build/installedfreetype/lib
checking if we can compile and link with freetype... no
configure: Could not compile and link with freetype. This might be a 32/64-bit mismatch.
configure: Using FREETYPE_CFLAGS=-I/home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/build/installedfreetype/include/freetype2 -I/home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/build/installedfreetype/include and FREETYPE_LIBS=-L/home/jenkins/workspace/SXA-openj9-xlinux-as/workspace/build/installedfreetype/lib -lfreetype
configure: error: Can not continue without freetype. You might be able to fix this by running 'sudo yum install freetype-devel'.
configure exiting with result code 1
```

**Comment by sxa555** [comment]
I have got it working on one of our build machines. I've put the binutils 2.28 utilities in `/usr/local/gcc/bin` along with the gcc 7.5 compiler and have set all `gcc75` builds to run on that machine for now (removed `gcc75` label from the others.

This should allow the jobs to start running again. If it works ok over the weekend I'll deploy to the other machines. The pre-build gcc 7.5 tarball which we use has been updated to include the new binutils now, so subsequent executions of the ansible playbooks will install it automatically

**Comment by jdekonin** [comment]
@sxa555 the OpenJ9 compile job doesn't download and compile freetype each time the compile triggers we use the default system package as installed via playbook.

**Comment by sxa555** [comment]
Yeah to be honest I don't know why adoptopenjdk set it up that way - it's something I wanted to revisit. However I think we bundle the freetype libs by default which would mean you're at the mercy of whatever the package manager puts on instead of a fixed version, so I would lean slightly towards using a separate, fixed version of the freetype code instead.

**Comment by DanHeidinga** [comment]
This has been addressed
