### PR TITLE
Win32 Compile Fix (TGC Parallel)

### PR DESCRIPTION
**Pull request by RSalman**
Fix for compile error on Windows IA32:
```
TgcParallel.cpp(308) : error C2220: warning treated as error - no
'object' file generated
TgcParallel.cpp(308) : warning C4244: '+=' : conversion from 'uint64_t'
to 'uintptr_t', possible loss of data
gmake[3]: *** [TgcParallel.obj] Error 2
```

- Cast `historyRecord->updates` to `(uintptr_t)`

Signed-off-by: Salman Rana <salman.rana@ibm.com>

### CODE REVIEW

**Comment by RSalman** [comment]
Compile failure from https://github.com/eclipse/openj9/pull/8614

**Comment by amicic** [comment]
Jenkins test sanity win32,win jdk8

**Comment by amicic** [comment]
Ideally, I'd like to avoid casting and align types of  totalRecordUpdates, historyRecord->updates, _copyScanUpdates... but since it would also  require OMR changes, I'll accept this temp solution.

File: runtime/gc_trace/TgcParallel.cpp [hunk 1]
```diff
@@ -305,7 +305,7 @@ tgcHookLocalGcEnd(J9HookInterface** hook, uintptr_t eventNum, void* eventData, v
 	uint64_t prevReadObjectBarrierUpdate = 0;
 #endif /* OMR_GC_CONCURRENT_SCAVENGER */
 	while (historyRecord < endRecord) {
-		totalRecordUpdates += historyRecord->updates;
+		totalRecordUpdates += (uintptr_t) historyRecord->updates;
```
Comment (keithc-ca) [inline runtime/gc_trace/TgcParallel.cpp]: Why the mix of different size types (`uintptr_t` and `uint64_t`)? Why not just `uint64_t` throughout?

Comment (RSalman) [reply runtime/gc_trace/TgcParallel.cpp]: These counts should all be `uintptr_t. They'll need to be all aligned to to use the same type, see https://github.com/eclipse/omr/issues/4825#issuecomment-589370296

Comment (RSalman) [reply runtime/gc_trace/TgcParallel.cpp]: These counts should all be `uintptr_t`. They'll need to be all aligned to to use the same type, see https://github.com/eclipse/omr/issues/4825#issuecomment-589370296.

Requires changes on the OMR side, will need to get PR in before making the counts consistent

Comment (keithc-ca) [reply runtime/gc_trace/TgcParallel.cpp]: If everything should be `uintptr_t` why is `uint64_t` used in this function (e.g. `totalRecordUpdates`)?

Comment (RSalman) [reply runtime/gc_trace/TgcParallel.cpp]: There's 3 different variables here:
-  `uint64_t` `historyRecord->updates`  
- `uintptr_t` `extensions->scavengerStats._copyScanUpdates` 
- `uintptr_t` `totalRecordUpdates`

There's no way to get around casting without any changes to OMR side. If we forgo casting 
`historyRecord->updates` here to `uintptr_t`, we'd have to change `totalRecordUpdates` `uint64_t` to match `historyRecord->updates`.... however then we'd need to cast `extensions->scavengerStats._copyScanUpdates`  to `uint64_t` a few lines down when we subtract `totalRecordUpdates` and `extensions->scavengerStats._copyScanUpdates`:
https://github.com/eclipse/openj9/blob/8782135e7f969dacae908af4c7c0d68511a94174/runtime/gc_trace/TgcParallel.cpp#L340

Comment (keithc-ca) [reply runtime/gc_trace/TgcParallel.cpp]: I hope we get this sorted out soon; casts are just a way to hide real problems.
