### ISSUE TITLE
Build break caused by GC_ObjectModel::SCAN_FLATTENED_ARRAY_OBJECT

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#7960]
Please add `case GC_ObjectModel::SCAN_FLATTENED_ARRAY_OBJECT:` to the `switch (_type)` statements in `restore()` and `save()` in `gc_glue_java/ObjectIterator.hpp`.  

I am seeing the following compiler errors:
```
In file included from ParallelGlobalGC.cpp:57:0:
../../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::restore(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:120:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT' not handled in switch [-Werror=switch]
   switch (_type) {
          ^
../../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::save(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:145:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT' not handled in switch [-Werror=switch]
   switch (_type) {
          ^
```

`SCAN_FLATTENED_ARRAY_OBJECT` was introduced by #7916.

**Comment by knn-k** [comment]
I am using GCC 7.3.1 for AArch64, with `-Werror` explicitly specified in the command line.

**Comment by pshipton** [comment]
The fix is https://github.com/eclipse/openj9/pull/7956

**Comment by pshipton** [comment]
Note you might follow the #triage channel in OpenJ9 slack for ongoing comments about build problems and test failures. https://openj9.slack.com/archives/CDS7QE9HB

**Comment by knn-k** [comment]
I searched for existing Issue for SCAN_FLATTENED_ARRAY_OBJECT before I opened this Issue.
I will check the Slack channel when I find any build failures next time.
