### ISSUE TITLE
Compilation fails on z/OS when compiling cl_se10

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#825]
Caused by #820

ERROR CCN3205 ./../unix/helpers.c:86    No valid offload key defined
CCN0793(I) Compilation failed for file ./../unix/helpers.c.  Object file not created.
FSUM3065 The COMPILE step ended with return code 12.
FSUM3017 Could not compile ../unix/helpers.c. Correct the errors and try again.

@JasonFengJ9

**Comment by JasonFengJ9** [comment]
Looking at it.

**Comment by DanHeidinga** [comment]
Also FYI @ChengJin01 - I know you're looking at getting the OpenJ9 (without an extensions repo) compiling on Z.  This may be an area that will need some tuning.

**Comment by pshipton** [comment]
Closing as this is an IBM internal problem.
