### PR TITLE
Merge PR-7292 from JITServer

### PR DESCRIPTION
**Pull request by a7ehuo**
PR #7292 eliminates `ClassEnv_getROMClassRefName` messages.

This commit also includes the latest update on `JITSERVER` in `JITClientCompilationThread.cpp` and `JITClientSession.cpp/hpp`.

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@mpirvu Ready for review. Thanks!

File: runtime/compiler/runtime/JITClientSession.cpp [hunk 1]
```diff
@@ -281,34 +281,15 @@ ClientSessionData::printStats()
    }
 
 ClientSessionData::ClassInfo::ClassInfo() :
-   _romClass(NULL),
```
Comment (mpirvu) [inline runtime/compiler/runtime/JITClientSession.cpp]: I think that we need to keep these initializations. As as a principle, a constructor should initialize all fields or none. Maybe order them so that all caches stay together.

Comment (a7ehuo) [reply runtime/compiler/runtime/JITClientSession.cpp]: Thought these were removed in the `jitaas` branch. I'll back port the change to `jitaas` branch in #7496.

**Comment by a7ehuo** [comment]
@mpirvu All comments addressed. Ready for another review. Thanks.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by mpirvu** [comment]
Some unrelated win64 failure
```
10:24:10  jvm.def : error LNK2001: unresolved external symbol JVM_GetExtendedNPEMessage
10:24:10  ../lib/jvm.lib : fatal error LNK1120: 1 unresolved externals
10:24:10  make[5]: *** [../makelib/targets.mk:462: ../lib/jvm.lib] Error 96
```

**Comment by mpirvu** [comment]
All the other tests passed, hence merging.

**Comment by knn-k** [comment]
This PR introduced a build failure in #7518.
