### ISSUE TITLE
32-bit doesn't compile SharedClassesMetaDataHelper.java

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6971]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/264
```
22:02:04  c:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR\openj9\debugtools\DDR_VM\src\com\ibm\j9ddr\vm29\pointer\helper\SharedClassesMetaDataHelper.java:31: error: cannot find symbol
22:02:04  			layer = j9shrOffset.cacheLayer().intValue();
22:02:04  			                   ^
22:02:04    symbol:   method cacheLayer()
22:02:04    location: variable j9shrOffset of type J9ShrOffsetPointer
```

Caused by https://github.com/eclipse/openj9/pull/6883

**Comment by hangshao0** [comment]
Will fix. I should use reflection.

**Comment by keithc-ca** [comment]
Why is `J9VM_OPT_MULTI_LAYER_SHARED_CLASS_CACHE` not defined for win32?

**Comment by hangshao0** [comment]
> Why is J9VM_OPT_MULTI_LAYER_SHARED_CLASS_CACHE not defined for win32?

We don't support multi-layer cache on 32 bit platforms.

**Comment by pshipton** [comment]
> We don't support multi-layer cache on 32 bit platforms.

Which was a design decision. Multi-layer increases the size of the cache slightly, and user's of 32-bit may not have extra space to spare. Given the limited space, multi-layer is less useful for 32-bit.
