### PR TITLE
Add getEnvironment() API to runtime helper table

### PR DESCRIPTION
**Pull request by NigelYiboYu**
Add a getEnvironment() API to the runtime helper table for PPC and
Z. The idea is to store function pointers on JIT initialization instead of storing unwrapped raw function entry addresses. In doing so, the JIT compiler is able to extract and use helper functions' environment pointers via the new getEnvironment() API. This is important for JITCODE to C function calls on PPC AIX and z/OS.

Also, rename TRS390_TOC_UNWRAP_ENV to TOC_UNWRAP_ENV so that the naming is
consistent with TOC_UNWRAP_ADDRESS.

Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>

### CODE REVIEW

**Comment by NigelYiboYu** [comment]
This pull request depends on OMR pull request: https://github.com/eclipse/omr/pull/2795

**Comment by NigelYiboYu** [comment]
This is the OpenJ9 portion of the runtime helper table change. 
@fjeremic

**Comment by NigelYiboYu** [comment]
This change passed my tests. Ready to review.

**Comment by fjeremic** [comment]
I'm making this as WIP until we have the reviews on the OMR side sorted out as the API naming may change.

**Comment by NigelYiboYu** [comment]
This is updated together with the OMR side. Ready for review.

**Comment by fjeremic** [comment]
Jenkins test sanity depends eclipse/omr#2795

**Comment by NigelYiboYu** [comment]
CI build failed with 

`
[ 86%] Building C object vm/CMakeFiles/j9vm.dir/rastrace.c.o
/home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/compiler/runtime/Runtime.cpp:170:67: error: no ‘void* TR_RuntimeHelperTable::getFunctionPointer(TR_RuntimeHelper)’ member function declared in class ‘TR_RuntimeHelperTable’
 void* TR_RuntimeHelperTable::getFunctionPointer(TR_RuntimeHelper h)
                                                                   ^
/home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/compiler/runtime/Runtime.cpp:178:77: error: no ‘void* TR_RuntimeHelperTable::getFunctionEntryPointOrConst(TR_RuntimeHelper)’ member function declared in class ‘TR_RuntimeHelperTable’
 void* TR_RuntimeHelperTable::getFunctionEntryPointOrConst(TR_RuntimeHelper h)
`

Seems like the OMR commit isn't rolled in the build.

**Comment by fjeremic** [comment]
Windows failures due to #2129.
