### PR TITLE
-Xcheck:jni ThrowNew() should check a jclass object

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Created a new type `JNIC_CLASSTHROWABLE` to check if a `jclass` object is a subclass of `java.lang.Throwable`;
Added `jniCheckJClassSubclass()` to check if a `jclass` argument is a subclass of an expected super class;
`checkThrowNew()` checks `JNIC_CLASSTHROWABLE`instead of `JNIC_JTHROWABLE`.

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@gacholio Could you please review?

File: runtime/jnichk/jnicheck.c [hunk 1]
```diff
@@ -79,6 +79,7 @@ static IDATA jniCheckParseOptions(J9JavaVM* javaVM, char* options);
 static IDATA jniCheckProcessCommandLine(J9JavaVM* javaVM, J9VMDllLoadInfo* loadInfo);
 static UDATA globrefHashTableHashFn(void *entry, void *userData);
 static UDATA globrefHashTableEqualFn(void *leftEntry, void *rightEntry, void *userData);
+static void jniCheckJClassSubclass(JNIEnv* env, const char* function, IDATA argNum, jobject aJobject, J9Class* expectedSupclass, const char* expectedType);
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.c:82]: To make it clearer, you should use jclass instead of jobject (and change the parameter name).

**Review by gacholio — APPROVED** [review]

File: runtime/jnichk/jnicheck.c (hunk 1 above)
Comment (JasonFengJ9) [reply runtime/jnichk/jnicheck.c]: Replaced `jobject aJobject` with `jclass aJclass`, please have another look.

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by JasonFengJ9** [comment]
```
16:00:27      [javac] /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java:258: error: cannot find symbol
16:00:27      [javac] 		String[] resetOptions = diagBean.queryDumpOptions();
16:00:27      [javac] 		                                ^
16:00:27      [javac]   symbol:   method queryDumpOptions()
16:00:27      [javac]   location: variable diagBean of type OpenJ9DiagnosticsMXBean
16:00:27      [javac] /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java:268: error: cannot find symbol
16:00:27      [javac] 		String[] options = diagBean.queryDumpOptions();
16:00:27      [javac] 		                           ^
16:00:27      [javac]   symbol:   method queryDumpOptions()
16:00:27      [javac]   location: variable diagBean of type OpenJ9DiagnosticsMXBean
16:00:27      [javac] /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java:375: error: cannot find symbol
16:00:27      [javac] 		String[] resetOptions = diagBeanRemote.queryDumpOptions();
16:00:27      [javac] 		                                      ^
16:00:27      [javac]   symbol:   method queryDumpOptions()
16:00:27      [javac]   location: variable diagBeanRemote of type OpenJ9DiagnosticsMXBean
16:00:27      [javac] /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java:387: error: cannot find symbol
16:00:27      [javac] 		String[] options = diagBeanRemote.queryDumpOptions();
16:00:27      [javac] 		                                 ^
16:00:27      [javac]   symbol:   method queryDumpOptions()
16:00:27      [javac]   location: variable diagBeanRemote of type OpenJ9DiagnosticsMXBean
16:00:27      [javac] Note: Some input files use or override a deprecated API.
16:00:27      [javac] Note: Recompile with -Xlint:deprecation for details.
16:00:27      [javac] Note: /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/JLM_Tests/src_80/org/openj9/test/java/lang/management/TestThreadInfo.java uses unchecked or unsafe operations.
16:00:27      [javac] Note: Recompile with -Xlint:unchecked for details.
16:00:27      [javac] 4 errors
16:00:27  
```
The failure is not related to this PR.

**Comment by JasonFengJ9** [comment]
It appears caused by https://github.com/eclipse/openj9/pull/11016
fyi @pshipton

**Comment by pshipton** [comment]
I think the problem is it's using the latest test material, but older OpenJ9 code. A rebase should fix it.

**Comment by JasonFengJ9** [comment]
Just rebased.
@pshipton please restart the PR test.

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
@JasonFengJ9 you mentioned having a test case, can it be added to the test suite in another PR?

**Review by pshipton — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
@pshipton Sure, will add the test in another PR.

**Comment by gacholio** [comment]
Adding tests for these things seems like a waste of time - it's not like it's going to break again in the future.

**Comment by JasonFengJ9** [comment]
The testcase referred at https://github.com/eclipse/openj9/pull/11047#issuecomment-719096376 didn't work in `zOS`  where the initial failure was reported, though the issue is reproduced in other platforms as well. So I have to figure out why the testcase doesn't apply to `zOS` first before adding it to automated test suite.
On the other hand a positive test does help to prevent a potential regression down the road.

**Comment by pshipton** [comment]
Until somebody makes another change sometime in the future and it does break. Having a good regression suite is valuable to avoid future regressions. We see existing regression tests finding problems. Having a test in the first place might have avoided introducing the bug this is fixing.
