### ISSUE TITLE
Setup eclipse CI integration for ibmruntimes/openj9-openjdk-jdk11 repo

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#2089]
Please can we setup CI integration for the openjdk extensions "head" (java 11) repository, similar to the jdk8/9/10 setups.... 

- copyright/line end checks
- nightly builds, build/sanity/extended
- PR builds

https://github.com/ibmruntimes/openj9-openjdk-jdk

Note the sanity/extended tests don't build yet for head/java11 - #2071

**Comment by pshipton** [comment]
@jdekonin fyi

**Comment by irinarada** [comment]
@jdekonin - do we have an ETA for these builds? We have many features that need testing...

**Comment by pshipton** [comment]
Note there are 2 things we want. 
1) Integration for ibmruntimes/openj9-openjdk-jdk11, which is the priority
2) Integratoin for ibmruntimes/openj9-openjdk-jdk, which is the head stream, used for Java 12 atm, and may not actually work at any given time, but we should get everything in place.

**Comment by jdekonin** [comment]
Copyright and LineEnding checks were done for JDK11 and JDK(next) repos under
ibmruntimes/openj9-openjdk-jdk11/issues/4
ibmruntimes/openj9-openjdk-jdk/issues/3

**Comment by jdekonin** [comment]
The build, sanity* and extended* pipelines are setup, although I cannot test until #2414 is merged.  The openjdk-test specific files have also not been created.  I believe @smlambert is doing this work under https://github.com/AdoptOpenJDK/openjdk-tests/pull/483

**Comment by llxia** [comment]
> The build, sanity* and extended* pipelines are setup

Even though the sanity* and extended* pipelines are setup, they need to be updated as we will need to pass in JAVA_VERSION as parameter and we will not have java version specific Jenkins file. For example, `openjdk11_ppc64_aix` will not be created.

**Comment by jdekonin** [comment]
AIX dependency details
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/411

**Comment by jdekonin** [comment]
Note that while the PR jobs have been created they appear to be very unstable wrt SDK compilation.  I am not certain if this is because of code or setup.  Existing PR jobs are not setup for general use until that can be determined.

**Comment by jdekonin** [comment]
For testing openjdk-jdk11 pull request builds I opened this PR.  All builds are triggering but there are some known failures for which I'll be raising defects.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/6

**Comment by jdekonin** [comment]
https://github.com/eclipse/openj9/issues/2468 - AIX
https://github.com/eclipse/openj9/issues/2469 - Windows apparently requires MSVC2017
https://github.com/eclipse/openj9/issues/2476 - pLinux compilation hangs, although it works sometimes
https://github.com/eclipse/openj9/issues/2388 & https://github.com/eclipse/openj9/issues/2329 - zLinux is slower than it should be, testing is very slow.

In my tests, I've been seeing occassional issues on xlinux as well.

**Comment by pshipton** [comment]
Please change xlinux to compile with gcc 7. Let me know if this is better handled via a separate issue.
zlinux as well if its working. Next week the slowness problems should be resolved by eclipse/omr#2796

**Comment by pshipton** [comment]
Actually, not sure zlinux compiles with gcc 7 yet, @babsingh is checking.

**Comment by babsingh** [comment]
JDK11 zLinux didn't compile with gcc-7.3.0. I saw two errors:
1) **error: module not found: jdk.hotspot.agent**
2) **error: array subscript is below array bounds**
```
/root/openj9-openjdk-jdk11/src/java.base/share/native/libfdlibm/k_rem_pio2.c: In function ‘__j__kernel_rem_pio2’:
/root/openj9-openjdk-jdk11/src/java.base/share/native/libfdlibm/k_rem_pio2.c:255:27: error: array subscript is below array bounds [-Werror=array-bounds]
                 for(k=1;iq[jk-k]==0;k++);   /* k = no. of terms needed */
                         ~~^~~~~~
```
Compilation stopped due to the second error. The second error is related to OpenJDK native code.

**Build log:** [jdk11_zlinux_build.log](https://github.com/eclipse/openj9/files/2233828/jdk11_zlinux_build.log)

**Comment by ChengJin01** [comment]
Already compiled with VS2013 and the latest JDK11 & OpenJ9 and my OMR changes.
```
...
A new configuration has been successfully created in
/cygdrive/c/temp/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release
using configure arguments '--disable-warnings-as-errors --with-boot-jdk=/cygdrive/c/temp/internal_jdk_10.0.1 --with-freemarker-jar=/cygdrive/c/temp/freemarker.jar'.

Configuration summary:
* Debug level:    release
* HS debug level: product
* JVM variants:   server
* JVM features:   server: 'cds cmsgc compiler1 compiler2 epsilongc g1gc graal jfr jni-check jvmci jvmti management nmt parallelgc serialgc services vm-structs'
* OpenJDK target: OS: windows, CPU architecture: x86, address length: 64
* Version string: 11-internal+0-adhoc.Administrator.openj9-openjdk-jdk11 (11-internal)

Tools summary:
* Environment:    cygwin version 2.10.0(0.325/5/3) (root at /cygdrive/c/cygwin64)
* Boot JDK:       openjdk version "10.0.1-adoptopenjdk" 2018-04-17  OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+10)  OpenJDK 64-Bit Server VM (build 10.0.1-adoptopenjdk+10, mixed mode)   (at /cygdrive/c/temp/internal_jdk_10.0.1)
* Toolchain:      microsoft (Microsoft Visual Studio 2013)
* C Compiler:     Version 18.00.21005.1 (at /cygdrive/c/progra~2/micros~3.0/vc/bin/amd64/cl)
* C++ Compiler:   Version 18.00.21005.1 (at /cygdrive/c/progra~2/micros~3.0/vc/bin/amd64/cl)

Build performance summary:
* Cores to use:   4
* Memory limit:   16383 MB
...
make all
...
Creating jdk image
Stopping sjavac server
Finished building target 'all' in configuration 'windows-x86_64-normal-server-release'
```

There is no problem with java -version
```
Administrator@JCHTORWIN101 /cygdrive/c/temp/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/images
$ jdk/bin/java  -version
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.Administrator.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-9db8db0e, JRE 11 Windows 8.1 amd64-64-Bit Compressed References 20180726_000000 (JIT enabled, AOT enabled)
OpenJ9   - 9db8db0e
OMR      - a96a2227
JCL      - e5c64f513d based on jdk-11+21)

Administrator@JCHTORWIN101 /cygdrive/c/temp/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/images
$ jdk/bin/java  -Xint -version
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.Administrator.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-9db8db0e, JRE 11 Windows 8.1 amd64-64-Bit Compressed References 20180726_000000 (JIT disabled, AOT disabled)
OpenJ9   - 9db8db0e
OMR      - a96a2227
JCL      - e5c64f513d based on jdk-11+21)
```

[jdk11_build_win_vs2013_log.txt](https://github.com/eclipse/openj9/files/2236407/jdk11_build_win_vs2013_log.txt)

**Comment by jdekonin** [comment]
#2527 opened to address openjdk next/head.  This issue covers jdk11 requirements.
This issue abstract should be changed to reflect actual work performed `...openjdk-jdk11...`

Remaining issues that shouldn't block the closure of this issue : 
#2468 - AIX
#2469 - Windows MSVC2017, isn't a blocker as jdk11 will compile on msvc2013
#2476 - pLinux compilation hangs, although it works sometimes

If there is agreement, I believe this can be closed.

**Comment by pshipton** [comment]
You could retry plinux. Keith mentioned it used to hang for him but doesn't any more.

**Comment by babsingh** [comment]
@pshipton JDK11 pLinux builds fine.
```
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.root.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-9f239b8, JRE 11 Linux ppc64le-64-Bit Compressed References 20180801_000000 (JIT enabled, AOT enabled)
OpenJ9   - 9f239b8
OMR      - ed95a04
JCL      - e4b4f66 based on jdk-11+24)
```
**Build log:** [jdk11_plinux_build.log](https://github.com/eclipse/openj9/files/2250297/jdk11_plinux_build.log)
