### ISSUE TITLE
JDK16 compilation error: cannot find symbol GenerateJLIClassesHelper.generateHolderClasses(traces)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10528]
Failure link
------------

https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_mac_OpenJDK/279/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:37:58  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java:1768: error: cannot find symbol
22:37:58                  return GenerateJLIClassesHelper.generateHolderClasses(traces);
22:37:58                                                 ^
22:37:58    symbol:   method generateHolderClasses(Stream<String>)
22:37:58    location: class GenerateJLIClassesHelper
```

Need a new stub method within `java.lang.invoke.GenerateJLIClassesHelper`.

**Comment by pshipton** [comment]
@babsingh fyi

**Comment by pshipton** [comment]
This must have been fixed already, since jdk16 is building now.

**Comment by babsingh** [comment]
The compile failure was fixed in https://github.com/eclipse/openj9/pull/10530.
