### PR TITLE
Handle unsupported scanner types in ObjectIterator

### LINKED ISSUE #7960: Build break caused by GC_ObjectModel::SCAN_FLATTENED_ARRAY_OBJECT
Please add `case GC_ObjectModel::SCAN_FLATTENED_ARRAY_OBJECT:` to the `switch (_type)` statements in `restore()` and `save()` in `gc_glue_java/ObjectIterator.hpp`.  

I am seeing the following compiler errors:
```
In file included from ParallelGlobalGC.cpp:57:0:
../../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::restore(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:120:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT' not handled in switch [-Werror=switch]
   switch (_type) {
          ^
../../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::save(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:145:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT' not handled in switch [-Werror=switch]
   switch (_type) {
          ^
```

`SCAN_FLATTENED_ARRAY_OBJECT` was introduced by #7916.

### PR DESCRIPTION
**Pull request by youngar**
There are two switch statements regarding the scanner type which are missing the default case. This results in the following warning:
```
In file included from HeapWalker.cpp:36:0:
../../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::restore(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:120:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT' not handled in switch [-Werror=switch
   switch (_type) {
         ^
./../../../gc_glue_java/ObjectIterator.hpp: In member function 'void GC_ObjectIterator::save(GC_ObjectIteratorState*)':
../../../../gc_glue_java/ObjectIterator.hpp:145:10: error: enumeration value 'SCAN_FLATTENED_ARRAY_OBJECT[m[K' not handled in switch [-Werror=switch]
   switch (_type) {
          ^
```
This was introduced in #7916 
cc @dmitripivkine

Fixes #7960

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity xlinux,zlinux jdk8
