### ISSUE TITLE
OSX 10.14 builds incompatible for 10.13

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#5791]
Using the latest shas, when I build on 10.14 using clang 9.1, the resulting binary does not work on 10.13.  A binary built on the 10.13 system does work on the 10.14 system.

The error I get is 
```
bash-3.2$ ./jdk/bin/java -version
dyld: Symbol not found: ___objc_personality_v0
  Referenced from: /private/tmp/./jdk/bin/java
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
 in /private/tmp/./jdk/bin/java
Abort trap: 6
```

fyi @babsingh

**Comment by pshipton** [comment]
> Using the latest shas, when I build on 10.14 using clang 9.1, the resulting binary does not work on 10.13

Makes sense. Similar problems occur on Linux as well. i.e. you can't build on Ubuntu 16 and run the resulting JVM on CentOS 6.

**Comment by babsingh** [comment]
> Makes sense. Similar problems occur on Linux as well. i.e. you can't build on Ubuntu 16 and run the resulting JVM on CentOS 6.

OpenJ9 built on OSX 10.14 should work till OSX 10.9 because the build scripts set `MACOSX_DEPLOYMENT_TARGET` (env. variable to 10.9). In summary, **XCode 9** may be incompatible on **OSX 10.14**. Below are the specific details for the above issue.

```
ld: warning: ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libz.dylib) built for (unknown). Note: This will be an error in the future.URGENT: building for OSX, but linking against dylib (/usr/lib/libiconv.dylib) built for (unknown). Note: This will be an error in the future.

ld: warning: ld: warning: ld: warning: URGENT: building for OSX, but linking against dylib (/System/Library/Frameworks/Security.framework/Security) built for (unknown). Note: This will be an error in the future.URGENT: building for OSX, but linking against dylib (/System/Library/Frameworks/Foundation.framework/Foundation) built for (unknown). Note: This will be an error in the future.
```

**72 errors** similar to the above two sample errors are seen when building OpenJ9 JDK11 on OSX with **XCode 9**: [linker_errors_osx_1014.log](https://github.com/eclipse/openj9/files/3192635/linker_errors_osx_1014.log). The issue is related to the functioning of the linker on **OSX 10.14 + Xcode 9**.

Other projects have experienced similar issues; example: https://github.com/golang/go/issues/27095. In this project, some people were able to resolve the issue: update OS or upgrade XCode version or don't use homebrew to install dependencies. Someone will have to verify if these solutions can be used with OpenJ9.

I also noticed other setup **differences between OSX 10.13 and 10.14**:
- **10.13** was using `bash version 4.4.23`, and **10.14** was using `bash version 5.0.3`.
- **10.13** had `darwin17.7.0`, and **10.14** had `darwin18.2.0`; guess: `darwin` corresponds to the OSX version.
- Due to different `darwin` versions, the `functionality of clang may also differ`.
- `pkg-config` was unavailable on **10.13** but available on **10.14**.
