### ISSUE TITLE
0.21.0 functional tests failing to compile

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10091]
The functional tests are failing to compile on the 0.21.0 release for Java 11 and 14.
Example failure https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Release_testList_1/4
```
11:59:29      [javac] /home/****/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Release_testList_1/openjdk-tests/functional/Java11andUp/src/org/openj9/test/condy/CondyGenerator.java:24: error: package org.objectweb.asm does not exist
11:59:29      [javac] import static org.objectweb.asm.Opcodes.ACC_PUBLIC;
11:59:29      [javac]                                ^
```
https://ci.eclipse.org/openj9/job/Pipeline-Release-0.21.0-Build11/11/
https://ci.eclipse.org/openj9/job/Pipeline-Release-0.21.0-Build14/5/

**Comment by pshipton** [comment]
I expect this is caused by the absence of https://github.com/eclipse/openj9/pull/10057 in the 0.21.0 release branch. Can we deliver this test change to the 0.21.0 release without causing any problems?
@theresa-m @llxia @DanHeidinga

**Comment by llxia** [comment]
yes, I think so. I will create a cherry-pick for the 0.21.0 release branch.

**Comment by pshipton** [comment]
Fixed by https://github.com/eclipse/openj9/pull/10092
