### PR TITLE
Change stackWalkerMaySkipFrames to avoid AOT failures

### PR DESCRIPTION
**Pull request by mpirvu**
Current implementation of TR_J9SharedCacheServerVM::stackWalkerMaySkipFrames
tries to avoid messages to the client by using a couple of calls to
`TR_J9ServerVM::isInstanceOf()`. However, under the covers, the call to
`TR_J9ServerVM::isInstanceOf()` will result into calls to
`TR_J9SharedCacheServerVM::getSuperClass()` which will check to see if
a SVM validation record for the given class is already present, which is
not. As a consequence, the SVM validation check will fail the AOT
compilation.
The solution implemented in this commit is more or less a workaround:
when SVM is used during an AOT compilation, do not try to optimize
`TR_J9SharedCacheServerVM::stackWalkerMaySkipFrames`, but rather send a
message to the client to find the answer.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by ymanton** [comment]
Jenkins test sanity xlinuxjit,plinuxjit jdk8

**Comment by mpirvu** [comment]
Java8 on xlinux failed with
```
Testing: rc018
Test start time: 2020/03/18 11:22:07 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump    -agentlib:jvmtitest=test:rc018 -cp "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 3 milliseconds
Time spent executing: 40135 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/1]:	testReflectRedefineAtSameTime
 [OUT] starting reflect worker threads
 [OUT] starting to populate java heap
 [ERR] JITServer is currently a technology preview. Its use is not yet supported
 [ERR] Unhandled exception
 [ERR] Type=Bus error vmState=0x00000000
 [ERR] J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000080
 [ERR] Handler1=00007F6DB694FE80 Handler2=00007F6DB62419F0 InaccessibleAddress=0000000000000000
 [ERR] RDI=0000000000CF5D00 RSI=00000000851311B8 RAX=0000000085130000 RBX=0000000085130000
 [ERR] RCX=0000000000CC2800 RDX=0000000000CD7A00 R8=0000000000CD7A00 R9=00000000020E0001
 [ERR] R10=0000000000000001 R11=0000000000000000 R12=000000008E6D7FF8 R13=00000000851311B8
 [ERR] R14=00000000854B4E18 R15=0000000000C43300
 [ERR] RIP=00007F6DB4EE1946 GS=0000 FS=0000 RSP=0000000000D1EBB8
 [ERR] EFlags=0000000000010216 CS=0033 RBP=2A7DC4B882FC02C0 ERR=0000000000000000
 [ERR] TRAPNO=000000000000000C OLDMASK=0000000000000000 CR2=00007F9B07C01000
...
 [ERR] Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
 [ERR] Module_base_address=00007F6DB456D000
```
I don't think current change is causing it, but I will launch the tests again.

**Comment by mpirvu** [comment]
Jenkins test sanity xlinuxjit jdk8

**Comment by a7ehuo** [comment]
The test runs with ` -Xgcpolicy:metronome` at the client, the failure could be related to #8707. 
It's also mentioned in: https://github.com/eclipse/openj9/pull/8837#issuecomment-598278200

```
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump    -agentlib:jvmtitest=test:rc018 -cp "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
```

**Comment by ymanton** [comment]
Failed again, this time trying to clone the test repo from GitHub. I'm satisfied that this change is clean enough.

**Comment by pshipton** [comment]
This breaks jkd8, jdk11 xlinux and plinux compilation, I'm reverting it.
```
22:21:41  /home/jenkins/jenkins-agent/workspace/Build_JDK8_ppc64le_linux_Nightly/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/control/JITClientCompilationThread.cpp: In function 'bool handleServerMessage(JITServer::ClientStream*, TR_J9VM*, JITServer::MessageType&)':
22:21:41  /home/jenkins/jenkins-agent/workspace/Build_JDK8_ppc64le_linux_Nightly/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/control/JITClientCompilationThread.cpp:580:25: error: 'VM_stackWalkerMaySkipFramesSVM' is not a member of 'JITServer::MessageType'
22:21:41         case MessageType::VM_stackWalkerMaySkipFramesSVM:
22:21:41                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ymanton** [comment]
Didn't realize this conflicted with #8832. Since that one was merged first, this one needs to be adapted.

**Comment by mpirvu** [comment]
@ ymanton I'll re-work this commit
