### ISSUE TITLE
Jenkins: Intermittent Git checkout failures on slave ub16-390-1 (LXEOJ901)

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1731]
Opening this as I've not found the root cause yet. We can use this to keep track of failures and discuss possible causes or solutions.

Failure when doing the `checkout scm` step ([here[(https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/builds/Build-JDK10-linux_390-64_cmprssptrs#L35) or [here](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_390-64_cmprssptrs#L37)) either in a Build* or Test* job. Only observed on [zLinux machine 1](https://ci.eclipse.org/openj9/computer/ub16-390-1/) so far.

#### Console output
```
00:00:18.848  > git rev-parse --is-inside-work-tree # timeout=10
00:00:18.882 Fetching changes from the remote Git repository
00:00:18.965  > git config remote.origin.url https://github.com/ibmruntimes/openj9-openjdk-jdk9.git # timeout=10
00:00:19.088 Fetching upstream changes from https://github.com/ibmruntimes/openj9-openjdk-jdk9.git
00:00:19.090  > git --version # timeout=10
00:00:19.123  > git fetch --tags --progress https://github.com/ibmruntimes/openj9-openjdk-jdk9.git +refs/heads/*:refs/remotes/origin/*
00:00:19.666  > git rev-parse refs/remotes/origin/openj9^{commit} # timeout=10
00:00:19.785  > git rev-parse refs/remotes/origin/origin/openj9^{commit} # timeout=10
00:00:19.801 Checking out Revision 0fe102d61baefed7c5165b5089873da67b7bf9b4 (refs/remotes/origin/openj9)
00:00:19.910  > git config core.sparsecheckout # timeout=10
00:00:19.925  > git checkout -f 0fe102d61baefed7c5165b5089873da67b7bf9b4
00:00:20.217  > git branch -a -v --no-abbrev # timeout=10
00:00:20.224  > git branch -D openj9 # timeout=10
00:00:20.239  > git checkout -b openj9 0fe102d61baefed7c5165b5089873da67b7bf9b4
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to ub16-390-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
		at com.sun.proxy.$Proxy76.withRepository(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.lang.NoClassDefFoundError: hudson.model.Computer
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:927)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:901)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:850)
	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:364)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Caused: java.io.IOException: Remote call on ub16-390-1 failed
	at hudson.remoting.Channel.call(Channel.java:958)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
	at com.sun.proxy.$Proxy76.withRepository(Unknown Source)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
	at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
#### Observed failures
https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/209/
https://ci.eclipse.org/openj9/job/Test-Sanity-JDK10-linux_390-64_cmprssptrs/15/
https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_390-64_cmprssptrs/152/
https://ci.eclipse.org/openj9/job/Build-linux_390-64_cmprssptrs/596/

#### Notes
- Lots of space on the machine.
- Doesn't appear to be related to the particular SHA we are checking out as it has happened to different SHAs.
- Doesn't appear to be related to a particular workspace as it has happened in different jobs
- The only action I've taken so far is to restart the machine

#### Possible Jenkins bugs reported
- [JENKINS-49402 - slave fails with java.lang.NoClassDefFoundError: hudson.model.Computer](https://issues.jenkins-ci.org/browse/JENKINS-49402)
- [JENKINS-50019 - java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer](https://issues.jenkins-ci.org/browse/JENKINS-50019)
No real answer in either of those yet.

###### Side Note: #1423 will partially help with this as it eliminates the failing step for Build* jobs

**Comment by AdamBrousseau** [comment]
Closing this as the failing piece of code is removed by #1423
