### ISSUE TITLE
Build failure with getReloKindFromGuardSite() in J9CodeGenerator.cpp

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#11814]
I see the following compilation error when I build with `TR_ASSERT()` enabled.  There is no variable `it` in the scope of `getReloKindFromGuardSite()`.

```
/root/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/compiler/../compiler/codegen/J9CodeGenerator.cpp:3044:32: error: 'it' was not declared in this scope
                               *it, site->getGuard(), site->getGuard()->getCallNode());
                                ^
```

This code was introduced by #11552.

**Comment by knn-k** [comment]
https://github.com/eclipse/openj9/blob/3f6faa8d961207fe5d7436ceeec257a190c4fc49/runtime/compiler/codegen/J9CodeGenerator.cpp#L3043-L3044

**Comment by dsouzai** [comment]
Oh, I guess because it's a TR_ASSERT it didn't get compiled on all the other platforms -_-. I'll open a fix tomorrow, but the fix is just
```
diff --git a/runtime/compiler/codegen/J9CodeGenerator.cpp b/runtime/compiler/codegen/J9CodeGenerator.cpp
index cf3225aba0..7c75c4ce56 100644
--- a/runtime/compiler/codegen/J9CodeGenerator.cpp
+++ b/runtime/compiler/codegen/J9CodeGenerator.cpp
@@ -3040,7 +3040,7 @@ static TR_ExternalRelocationTargetKind getReloKindFromGuardSite(TR::CodeGenerato
             type = TR_CheckMethodExit;
          else
             TR_ASSERT(0,"Unexpected TR_MethodEnterExitGuard at site %p guard %p node %p\n",
-                              *it, site->getGuard(), site->getGuard()->getCallNode());
+                              site, site->getGuard(), site->getGuard()->getCallNode());
          break;
 
       case TR_RemovedProfiledGuard:
```

**Comment by knn-k** [comment]
This is not an AArch64 problem.  I just enabled `TR_ASSERT()` for debugging.
